### ISSUE TITLE
Automate gathering the data

### ISSUE THREAD

**Issue by aaronraimist** [aaronraimist/FAA-Preliminary-Accident-and-Incident-Data#1]
https://jasonet.co/posts/scheduled-actions/
https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/

**Comment by YesTrustMe** [comment]
Hi. Please continue to update your don't fuck with paste extension. Chrome will disable it next year. Thanks. 

> https://jasonet.co/posts/scheduled-actions/ https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/
